# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np  # installed in venv 'test'

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
np.__version__

'1.19.1'

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [14]:
arr = np.ones((3,3))
print(arr)
print("arr.size is no.of elements in arr : ", arr.size)
memory_size = arr.size*arr.itemsize
print("Memory Size: %d bytes" %memory_size)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr.size is no.of elements in arr :  9
Memory Size: 72 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [2]:
# help (np.add)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [22]:
array = np.zeros(10)
array[4]=1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [30]:
ar_range=np.arange(10,50,1)
print(type(ar_range))
print(ar_range.shape)
print(ar_range)
print(ar_range.reshape(8,5))

<class 'numpy.ndarray'>
(40,)
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [47]:
print(ar_range)
print('='*20)

rev_ar = ar_range[::-1]
print(rev_ar)
print('='*20)

res_ar = ar_range.reshape(8,5)
print(res_ar)
print('='*20)

rev_ar1= res_ar[::-1] # will reverse rows only

print(rev_ar1)
print('='*20)

ar_flip=np.flip(res_ar)
print(ar_flip)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[45 46 47 48 49]
 [40 41 42 43 44]
 [35 36 37 38 39]
 [30 31 32 33 34]
 [25 26 27 28 29]
 [20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]]
[[49 48 47 46 45]
 [44 43 42 41 40]
 [39 38 37 36 35]
 [34 33 32 31 30]
 [29 28 27 26 25]
 [24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]]


* array[::-1] 
* np.flip(array)
* np.fliplr(array) # flips columns
* np.flipud(array) # flips rowa

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [48]:
mat_33 = np.arange(0,9).reshape(3,3)
print(mat_33)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [54]:
ar = np.array((1,2,0,0,4,0))
print(ar)
ar_nonzero = np.where(ar!=0)
print(ar_nonzero)


[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [58]:
idtt = np.identity(3)
print(idtt)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [65]:
ar_rand = np.random.rand(3,3,3)
print(ar_rand)

[[[0.69213675 0.04294299 0.8335869 ]
  [0.36994852 0.936557   0.48305288]
  [0.12533161 0.96445418 0.01702583]]

 [[0.67657077 0.14043997 0.15531285]
  [0.64955775 0.98165422 0.69480742]
  [0.76197389 0.42520918 0.13889344]]

 [[0.2161863  0.76470027 0.05460587]
  [0.49012299 0.18069018 0.63092485]
  [0.55124203 0.56708121 0.81834498]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [76]:
arr = np.random.randint(low=101, size=(5,2))
print(arr)
print("Max value: ",np.max(arr))
print("Min value: ", np.min(arr))

[[ 2 84]
 [90 45]
 [29 71]
 [50 99]
 [59 10]]
Max value:  99
Min value:  2


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [81]:
vec = np.random.rand(30)
print(vec)
print("="*50)
vec_mean = np.mean(vec)
print("Mean : ", vec_mean )


[0.3515714  0.44294568 0.57949344 0.61756091 0.17711749 0.86498179
 0.71027069 0.17063169 0.85508266 0.01985662 0.64168373 0.16233435
 0.25755049 0.34260646 0.00614414 0.43855106 0.79704411 0.67566494
 0.54502309 0.56422699 0.01398415 0.60897714 0.98856638 0.22410702
 0.58721772 0.83505795 0.79249758 0.329228   0.35720256 0.96011296]
Mean :  0.497243106178883


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [93]:
arr = np.zeros((1,1))
print(arr)
print("Dimension:", arr.ndim)
bdr_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=1)
print(bdr_arr)

[[0.]]
Dimension: 2
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [96]:
bdr_zero = np.pad(bdr_arr, pad_width=1, mode='constant', constant_values=0)
print(bdr_zero)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [102]:
'''python
0 * np.nan = nan
np.nan == np.nan --> False
np.inf > np.nan --> False
np.nan - np.nan --> nan
np.nan in set([np.nan]) -->True
0.3 == 3 * 0.1 -->False
'''

'python\n0 * np.nan = nan\nnp.nan == np.nan --> False\nnp.inf > np.nan --> False\nnp.nan - np.nan --> nan\nnp.nan in set([np.nan]) -->True\n0.3 == 3 * 0.1 -->False\n'

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [105]:
arr = np.arange(1,5)
ans = np.diag(arr, k=-1)
print(ans)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [111]:
x = np.ones((6,6))
y = np.tril(x,k=0)
print(y)

[[1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [124]:
arr = np.ones((8,8))
arr[1::2,::2]=0 # 1::2--> starting from 1st row, to all in the step of 2 rows     
arr[::2,1::2]=0  # ::2 --> every second row and column
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [136]:
arr = np.random.randint(low=101 , size = (6,7,8))
np.unravel_index(99, (6,7,8) )

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [145]:
arr=np.array([[1,0], [0,1]])
arr.shape
tile_ar = np.tile(arr, (2,2))
tile_ar

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [156]:
array = np.random.random((5,5))
print(array)
mean=np.mean(array)
std=np.std(array)

normalize_array = (array-mean)/std

normalize_array1 = (array-(np.min(array)))/(np.max(array) - np.min(array))
print(normalize_array)
print(normalize_array1)

[[0.67486676 0.24271869 0.61576379 0.34073584 0.09847581]
 [0.52497158 0.97484746 0.93605084 0.90247706 0.76669413]
 [0.24313753 0.87684399 0.63531983 0.62889946 0.57065883]
 [0.47334156 0.71409228 0.53050627 0.00101185 0.17564654]
 [0.72531862 0.49922335 0.84749918 0.34036697 0.28318773]]
[[ 0.48578047 -1.12954926  0.264859   -0.76317016 -1.66871587]
 [-0.07451391  1.60708075  1.46206253  1.33656685  0.82902274]
 [-1.12798366  1.24075278  0.33795768  0.31395893  0.09626082]
 [-0.2675022   0.63240186 -0.05382575 -2.03302719 -1.38025878]
 [ 0.67436488 -0.17075844  1.13106458 -0.76454896 -0.97827972]]
[[0.69195961 0.24820086 0.63126869 0.34885148 0.10008256]
 [0.53803714 1.         0.96016101 0.9256852  0.78625414]
 [0.24863096 0.89936343 0.65135015 0.64475729 0.58495189]
 [0.48501996 0.73223902 0.54372054 0.         0.17932666]
 [0.74376697 0.51159712 0.86923021 0.3484727  0.2897572 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [163]:
# unsigned bytes = ubytes
custom_color = np.dtype([("r", np.ubyte, (1,)), ("g", np.ubyte, (1,)), ("b", np.ubyte, (1,)), ("a", np.ubyte, (1,))])
custom_color

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [173]:
ar_1 = np.random.randint(low = 10, size =(5,3))
ar_2 = np.random.random((3,2))

multiply = np.dot(ar_1,ar_2)
multiply

array([[ 6.42137656,  7.52134867],
       [ 1.5429724 ,  1.15474142],
       [ 7.25208083,  5.37022598],
       [14.26585649, 12.95239899],
       [ 4.83529677,  3.37901002]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [10]:
array = np.arange(15)
array[(array>3) & (array < 8)] *= -1
array

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [14]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [15]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Saurabh\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Saurabh\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [20]:
array = np.random.uniform(-10,+10,20)
print(array)
print(np.copysign(np.ceil(np.abs(array)), array))
print(np.where(array>0, np.ceil(array), np.floor(array)))


[-4.6279939  -6.2687542  -2.99503949  6.41013321 -9.8679275   7.82679211
 -2.32206229 -7.61363908 -1.41415643 -3.14249499 -5.38593685 -8.68259659
 -2.84919365  9.92807395  5.30873117 -9.34134214  8.24038902 -5.28175471
 -4.47809563  7.17487914]
[ -5.  -7.  -3.   7. -10.   8.  -3.  -8.  -2.  -4.  -6.  -9.  -3.  10.
   6. -10.   9.  -6.  -5.   8.]
[ -5.  -7.  -3.   7. -10.   8.  -3.  -8.  -2.  -4.  -6.  -9.  -3.  10.
   6. -10.   9.  -6.  -5.   8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
arr_1 = np.random.randint(0,10,(5,5,5))
arr_2 = np.random.randint(0,20,(4,3))
print(arr_1.ndim)
np.intersect1d(arr_1, arr_2)

3


array([2, 3, 4, 5, 6, 7])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Saurabh\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [46]:
import datetime
today = (datetime.datetime.now())
print("Today::",today)
tommorow = today + datetime.timedelta(days=1)
print("Tommorow::",tommorow)
yesterday = today-datetime.timedelta(days=1)
print("Yesterday::",yesterday)

Today:: 2020-12-07 18:39:18.581050
Tommorow:: 2020-12-08 18:39:18.581050
Yesterday:: 2020-12-06 18:39:18.581050


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [51]:
dates_july = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates_july)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [62]:
A = np.random.randint(5,15,(4,3))
B = np.random.randint(10,20,(4,3))
sum_ = np.add(A,B)
div = A*(-1/2)
result = np.multiply(sum_,div)
print(result)

[[-159.5  -91.  -130. ]
 [-112.5 -150.   -80.5]
 [-208.  -125.  -150. ]
 [ -37.5  -80.  -126.5]]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [68]:
array = np.random.uniform(0,10,(4,4))
print(array)
print(np.floor(array))
print(np.ceil(array))

[[1.47793638 7.83363594 0.74601547 7.50891687]
 [4.7157286  1.59799853 7.49265689 4.63849255]
 [3.98898154 7.44289901 7.93011297 7.83854752]
 [0.83797326 6.2108347  4.11578076 1.07567802]]
[[1. 7. 0. 7.]
 [4. 1. 7. 4.]
 [3. 7. 7. 7.]
 [0. 6. 4. 1.]]
[[2. 8. 1. 8.]
 [5. 2. 8. 5.]
 [4. 8. 8. 8.]
 [1. 7. 5. 2.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [77]:
array = np.zeros((5,5))
array+=np.arange(0,5)
print(array)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [81]:
mygen = (i for i in range (10))
x = np.stack(mygen)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
def generate():
    for i in range(10):
        yield i
arr = np.fromiter(generate(),dtype=float,count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)